# Generated by Django 3.2 on 2022-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='category_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='blog/static/img'),
        ),
    ]
