# Generated by Django 3.2 on 2022-02-21 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='category_img',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='img',
            field=models.ImageField(default='', upload_to='blog/static/img/categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
