# Generated by Django 3.2.10 on 2022-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220317_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/static/img/profiles/default_avatar.png', upload_to='blog/static/img/profiles'),
        ),
    ]
