# Generated by Django 3.2.10 on 2022-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/static/img/profiles/default_avatar.png', upload_to='blog/static/img/profiles', verbose_name='Аватар'),
        ),
    ]
