# Generated by Django 3.2.10 on 2022-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_avatar_comment_avatarop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/static/img/profiles/d.png', upload_to='blog/static/img/profiles', verbose_name='Аватар'),
        ),
    ]
